### ISSUE TITLE
Elements not hiding after mouseout

### ISSUE THREAD

**Issue by ramenchef** [dnsev-h/h-links#1] opened 2015-10-03 03:32 UTC
Chrome Dev + Tampermonkey BETA. The gallery details persist even without highlighting a link.

**Comment by dnsev-h** [comment] 2015-10-03 03:48
I've seen this problem in development, but thought I fixed it, and I currently cannot reproduce this.

Are you using any additional scripts (4chan-x, inline script)?

**Comment by ramenchef** [comment] 2015-10-03 04:11
I am running 4chan-x (ccd0 version), oneechan, and linkify plus plus. After enabling and disabling various scripts/extensions, it seems like oneechan is the one causing the issue.

**Comment by dnsev-h** [comment] 2015-10-03 04:12
Alright, I'll look into what it's doing.

**Comment by dnsev-h** [comment] 2015-10-03 05:27
Should now be fixed in [1.0.1](https://github.com/dnsev-h/h-links/commit/ec729ed2ec8d754ef228818cbd737eb810e96ec2)

Was a priority issue with OneeChan's !important's.

**Closed by dnsev-h** 2015-10-03 05:27 UTC
